# This is a basic workflow to help you get started with Actions

name: SC_DEMO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: main
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-snowflake-changes-job:
     runs-on: ubuntu-latest
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Use Python 3.12.x
        uses: actions/setup-python@v2.2.1
        with:
         python-version: 3.12.x
       

      # Runs a set of commands using the runners shell
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ variables.SF_ACCOUNT }}
          SF_DATABASE: ${{ variables.SF_DATABASE }}
          SF_ROLE: ${{ variables.SF_ROLE }}
          SF_WH: ${{ variables.SF_WH }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WH -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
